Fix: failure to update some full partitioned images.

diff --git a/devops/flasher.patch b/devops/flasher.patch
--- a/devops/flasher.patch
+++ b/devops/flasher.patch
@@ -1,6 +1,6 @@
 diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-eMMC-flasher.sh
---- ./beaglebone-black-eMMC-flasher.sh	2015-10-22 22:22:42.645844935 +0200
-+++ ../tools_updated/beaglebone-black-eMMC-flasher.sh	2015-11-19 02:16:58.000000000 +0200
+--- ./beaglebone-black-eMMC-flasher.sh	2015-11-25 06:32:08.418396703 +0200
++++ ../tools_updated/beaglebone-black-eMMC-flasher.sh	2015-11-25 07:01:41.726316364 +0200
 @@ -1,4 +1,6 @@
  #!/bin/bash -e
 +
@@ -36,7 +36,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  fi
  
  flush_cache () {
-@@ -52,11 +60,11 @@
+@@ -52,12 +60,14 @@
  
  flush_cache_mounted () {
  	sync
@@ -46,21 +46,25 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  
  write_failure () {
 -	echo "writing to [${destination}] failed..."
+-
 +	echo "writing to [${emmcdev}] failed..."
- 
++#lsblk
++#df -h
++#exit 0
  	if [ -e /sys/class/leds/beaglebone\:green\:usr0/trigger ] ; then
  		echo heartbeat > /sys/class/leds/beaglebone\:green\:usr0/trigger
-@@ -66,17 +74,23 @@
+ 		echo heartbeat > /sys/class/leds/beaglebone\:green\:usr1/trigger
+@@ -66,20 +76,27 @@
  	fi
  	echo "-----------------------------"
  	flush_cache
 -	umount ${destination}p1 || true
 -	umount ${destination}p2 || true
 +
-+	umount ${emmcdev}p1 || true
-+	umount ${emmcdev}p2 || true
-+        umount ${emmcdev}p3 || true
-+        umount ${emmcdev}p4 || true
++	umount ${emmcdev}p1 > /dev/null || true
++	umount ${emmcdev}p2 > /dev/null || true
++        umount ${emmcdev}p3 > /dev/null || true
++        umount ${emmcdev}p4 > /dev/null || true
 +
  	exit
  }
@@ -78,7 +82,11 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  }
  
  check_running_system () {
-@@ -87,12 +101,12 @@
++
+ 	if [ ! -f /boot/uboot/uEnv.txt ] ; then
+ 		echo "Error: script halting, system unrecognized..."
+ 		echo "unable to find: [/boot/uboot/uEnv.txt] is ${source}p1 mounted?"
+@@ -87,12 +104,12 @@
  	fi
  
  	echo "-----------------------------"
@@ -94,7 +102,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  		write_failure
  	fi
  }
-@@ -116,7 +130,7 @@
+@@ -116,7 +133,7 @@
  }
  
  fdisk_toggle_boot () {
@@ -103,7 +111,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  	a
  	1
  	w
-@@ -125,38 +139,66 @@
+@@ -125,38 +142,66 @@
  }
  
  format_boot () {
@@ -177,7 +185,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  		umount ${DRIVE} >/dev/null 2>&1 || umount -l ${DRIVE} >/dev/null 2>&1 || write_failure
  	done
  
-@@ -166,23 +208,13 @@
+@@ -166,23 +211,13 @@
  
  	format_boot
  	format_root
@@ -205,7 +213,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  	if [ "${root_uuid}" ] ; then
  		root_uuid="UUID=${root_uuid}"
  		device_id=$(cat /tmp/boot/uEnv.txt | grep mmcroot | grep mmcblk | awk '{print $1}' | awk -F '=' '{print $2}')
-@@ -195,13 +227,105 @@
+@@ -195,13 +230,104 @@
  		root_uuid="${source}p2"
  	fi
  	flush_cache_mounted
@@ -218,7 +226,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +	#Make sure the BootLoader gets copied first:
 +
 +	echo "debug: Removing everything on boot partition first!"
-+	rm -r /tmp/boot/*
++#	rm -r /tmp/boot/*
 +
 +	echo "debug: copy 1"
 +	cp -v /boot/uboot/MLO /tmp/boot/MLO || write_failure
@@ -231,7 +239,8 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +	echo "debug: copy 3"
 +	#this command should fail as we are copying to a fat partition and we cant set permissions for fat
 +	rsync -aAXv /boot/uboot/ /tmp/boot/ --exclude={MLO,u-boot.img,*bak,flash-eMMC.txt,flash-eMMC.log} || true #write_failure
-+	flush_cache_mounted
++echo "done rsync3"	
++flush_cache_mounted
 +
 +	set_boot_uuid
  	umount_p1
@@ -267,9 +276,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +}
 +
 +alldone () {
-+
 +	#exit
-+
 +	if [ -e /sys/class/leds/beaglebone\:green\:usr0/trigger ] ; then
 +		echo default-on > /sys/class/leds/beaglebone\:green\:usr0/trigger
 +		echo default-on > /sys/class/leds/beaglebone\:green\:usr1/trigger
@@ -283,7 +290,6 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +	echo "Note: Actually unpower the board, a reset [sudo reboot] is not enough."
 +	echo "-----------------------------"
 +
-+
 +	echo "Removing uEnv..."
 +	cp /boot/uboot/uEnv.txt /boot/uboot/uEnv.txt.org
 +
@@ -294,25 +300,26 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +	sync
 +	sleep 5
 +
-+
 +	#shutdown now
-+	halt
++	#halt
 +}
 +
  copy_rootfs () {
  	mkdir -p /tmp/rootfs/ || true
 -	mount ${destination}p2 /tmp/rootfs/ -o async,noatime
 +	mount ${emmcdev}p2 /tmp/rootfs/ -o async,noatime
-+	echo "debug: rsync"
++	echo "debug: rsync4"
++	lsblk
  	rsync -aAXv /* /tmp/rootfs/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/boot/*,/lib/modules/*} || write_failure
 +
++	echo "Done rsync4!"
 +	mkdir /tmp/rootfs/data/ || true
 +	mkdir /tmp/rootfs/perm/ || true
 +
  	flush_cache_mounted
  
  	if [ -f /tmp/rootfs/opt/scripts/images/beaglebg.jpg ] ; then
-@@ -214,14 +338,17 @@
+@@ -214,14 +340,17 @@
  
  	mkdir -p /tmp/rootfs/boot/uboot/ || true
  	mkdir -p /tmp/rootfs/lib/modules/$(uname -r)/ || true
@@ -331,7 +338,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
  	if [ "${boot_uuid}" ] ; then
  		boot_uuid="UUID=${boot_uuid}"
  	else
-@@ -238,26 +365,89 @@
+@@ -238,26 +367,93 @@
  	flush_cache_mounted
  	umount_p2
  
@@ -365,7 +372,6 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +rootfs_size=$(( (emmc_sectors - 8*1024*2 - 512*1024*2 - 96*1024*2 - 2*1024*2)/1024/2 ))
 +echo "rootfs size: $rootfs_size M"
 +
-+
 +perm_lastsector=$((emmc_sectors - 1))
 +perm_firstsector=$((perm_lastsector - 8*1024*2))
 +data_lastsector=$((perm_firstsector - 1 ))
@@ -397,6 +403,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +then
 +        write_boot_image
 +else
++	format_boot
 +        copy_boot
 +fi
 +
@@ -413,6 +420,7 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +then
 +	write_rootfs_image
 +else
++	format_root
 +        copy_rootfs
 +fi
 +
@@ -439,10 +447,13 @@ diff -urN ./beaglebone-black-eMMC-flasher.sh ../tools_updated/beaglebone-black-e
 +
 +alldone
 +
-+shutdown now
++shutdown -h now
++poweroff
++
++
 diff -urN ./make_factory_settings_sdcard.sh ../tools_updated/make_factory_settings_sdcard.sh
 --- ./make_factory_settings_sdcard.sh	1970-01-01 02:00:00.000000000 +0200
-+++ ../tools_updated/make_factory_settings_sdcard.sh	2015-11-02 11:49:28.000000000 +0200
++++ ../tools_updated/make_factory_settings_sdcard.sh	2015-11-25 06:32:08.362396705 +0200
 @@ -0,0 +1,172 @@
 +#!/bin/sh
 +
@@ -618,7 +629,7 @@ diff -urN ./make_factory_settings_sdcard.sh ../tools_updated/make_factory_settin
 +# reboot
 diff -urN ./pack_latest_version.sh ../tools_updated/pack_latest_version.sh
 --- ./pack_latest_version.sh	1970-01-01 02:00:00.000000000 +0200
-+++ ../tools_updated/pack_latest_version.sh	2015-11-02 11:49:28.000000000 +0200
++++ ../tools_updated/pack_latest_version.sh	2015-11-25 06:32:08.382396704 +0200
 @@ -0,0 +1,165 @@
 +#!/bin/bash
 +
@@ -787,7 +798,7 @@ diff -urN ./pack_latest_version.sh ../tools_updated/pack_latest_version.sh
 +exit 0
 diff -urN ./restore_factory_settings.sh ../tools_updated/restore_factory_settings.sh
 --- ./restore_factory_settings.sh	1970-01-01 02:00:00.000000000 +0200
-+++ ../tools_updated/restore_factory_settings.sh	2015-11-04 00:10:19.369442628 +0200
++++ ../tools_updated/restore_factory_settings.sh	2015-11-25 06:32:08.386396704 +0200
 @@ -0,0 +1,115 @@
 +#!/bin/bash -e
 +
@@ -906,7 +917,7 @@ diff -urN ./restore_factory_settings.sh ../tools_updated/restore_factory_setting
 +lable_partitions
 diff -urN ./unpack_latest_version.sh ../tools_updated/unpack_latest_version.sh
 --- ./unpack_latest_version.sh	1970-01-01 02:00:00.000000000 +0200
-+++ ../tools_updated/unpack_latest_version.sh	2015-11-02 12:25:30.000000000 +0200
++++ ../tools_updated/unpack_latest_version.sh	2015-11-25 06:32:08.386396704 +0200
 @@ -0,0 +1,325 @@
 +#!/bin/bash
 +
